### ISSUE TITLE
simple URI thumbnails are not supported

### ISSUE THREAD

**Issue by barmintor** [sul-dlss/iiif-evented-canvas#4]
Another gallica thumbnail issue, eg http://gallica.bnf.fr/iiif/ark:/12148/btv1b10500001g/manifest.json

> "thumbnail" : {
>       "@id" : "http://gallica.bnf.fr/ark:/12148/btv1b10500001g/f352.thumbnail"
>     }

In this case, there's obvious image file extension or format, but also no `service` for the resource. In this case, should the library use the `@id` uri unmodified?

The manifests work with something like:

> if (Object.keys(resource).length == 1 && resource['@id']) return resource['@id'];

**Comment by barmintor** [comment]
I believe this is what is triggering https://github.com/ProjectMirador/mirador/issues/1452

**Comment by regisrob** [comment]
Any update about how to go forward on this bug?

**Comment by barmintor** [comment]
Summing up, errors come from these scenarios:
1. Thumbnail property can be a string - should use the string as the URI
2. Thumbnail property can be an object without `"@service"` - should use `"@id"` as the URI
3. Thumbnail URI may not have a file extension - should use unmodified

I think these emanate from https://github.com/sul-dlss/iiif-evented-canvas/blob/master/src/thumbnailFactory.js#L39-L46

**Comment by regisrob** [comment]
Right, I have proposed a small fix a few months ago that worked for me, but there has been no follow-up on this at all, so it may not be an acceptable solution, I guess...
https://github.com/ProjectMirador/mirador/issues/1452#issuecomment-312257457

**Comment by mikeapp** [comment]
This is breaking Getty manifests as well, which have a string/URI only
