### ISSUE TITLE
manifest canvases bounds with quoted values do not render

### ISSUE THREAD

**Issue by christopher-johnson** [sul-dlss/iiif-evented-canvas#5]
If canvas bounds are not cast as integers  [here](https://github.com/sul-dlss/iiif-evented-canvas/blob/master/src/canvasObject.js#L20-L21), then bounds are not able be computed.  

This then produces this error:
`Uncaught TypeError: Cannot read property '_transformBounds' of null`
 
This is related to an issue that I have raised here: https://github.com/IIIF/iiif.io/issues/1252

I can submit a PR for this as I have tested the fix which is to wrap config.canvas.height and config.canvas.width with parseInt();

**Comment by azaroth42** [comment]
Noting that 2.x asserts integers as integers. #1252, if accepted, would only take effect in 3.0

**Comment by aeschylus** [comment]
Thanks for that clarification @azaroth42. Seems worth it to cover that case.

**Comment by azaroth42** [comment]
Perhaps you misunderstood -- the manifest is invalid if it requires parseInt() or parseFloat(). The likelihood of that changing in 3.0 is also very low.  You would also need to check it in embedded info.json fields, on total and startIndex, in 3.0 checking that duration is a float, and have the impossible problem of determining whether extension properties should be transformed from strings into integers or floats.

**Comment by aeschylus** [comment]
In that case, I did misunderstand. Very glad for the updated strictness regarding type, for those reasons. Perhaps a `console.warn` is more appropriate here then.

**Comment by aeschylus** [comment]
The change has been reverted.

Out of curiosity, @christopher-johnson, are you using this module (`iiif-evented-canvas`) outside of Mirador, or are Mirador bugs bringing you here?

**Comment by christopher-johnson** [comment]
@aeschylus My intention is to address a problem at UBL because they have been producing manifests (several thousand now) with numeric values being quoted.  None of these work with Mirador since the introduction of `iiif-evented-canvas`.  

The important issue here is to have clarity on specification compliance for API validation.  And it appears that the ruling has been made that the JSON schema (not JSON-LD `@context`) will govern the IIIF.  

For LDP implementations, serializing ordinary JSON from RDF can be problematic as there are several dataypes that are not supported by the JSON schema (like date).  As an immediate solution to this issue, I may try and patch the JSON-LD processor with a shortcut serialization for unquoted integers from ^^xsd:integer datatype (similar to Turtle).  

IMHO, depending on JSON over RDF is not a good long-term decision and may severely constrain vocabulary design, though it may lower the cost and complexity for interface development.

**Comment by christopher-johnson** [comment]
footnote: I have learned that jsonld-java processor has an option "useNativeTypes".  This produces JSON schema compliant integers.
